### ISSUE TITLE
wrong pass error on good password

### ISSUE THREAD

**Issue by tiquis0290** [the-marenga/sf-api#37]
Hi yeasterday i tried your project, (it was pain for me to run it, because of lack of rust skills, but i got to point where it's work)
but when i enter my character name password and server i got this error 
**ServerError("wrong pass")**
i guess it's mean bad password but iam sure its right,
than i tried diffeent server and got player doesnt exist  so i am sure that iam trieing the right server with right name and password,
any tips how to fix it?
p.s server is s10.sfgame.eu

**Comment by the-marenga** [comment]
Are you trying to access a character, that is associated with an SFAccount?

**Comment by the-marenga** [comment]
In that case you would have to use the SFAccount and get all associated charactersessions from that, instead of creating the charactersessions manually.

**Comment by tiquis0290** [comment]
iam not sure what type fo account it is, is there easy way to check it settings or something like that?

**Comment by tiquis0290** [comment]
thx a lot your i am just dumb it is sfaccount, before i wrote here  ithought  i tested both options but i forget to change name and password so it contain your demo "username" and pass : "pwassword"
