### ISSUE TITLE
unlocking dungeon

### ISSUE THREAD

**Issue by tiquis0290** [the-marenga/sf-api#55]
I found Command::UnlockFeature { unlockable: Unlockable { main_ident: (), sub_ident: () } } ant thing its the intended way but i am not able to figure out what to pass  as main_ident and sub_ident?

**Comment by the-marenga** [comment]
`Unlockables` contains a `pending_unlocks` field, which is Vec<Unlockable>. These are all the things you can unlock. Each unlock contains:

``` Rust
pub struct Unlockable {
    /// Something like `Dungeon-key`
    pub main_ident: i64,
    /// Would be a specification of the main ident like for which dungeon
    pub sub_ident: i64,
}
```

These are the main and sub idents required in the command

**Comment by tiquis0290** [comment]
thx i missed it when looking through.
mby i next released comment about here to get this  will be good
