### ISSUE TITLE
missing commands for pets

### ISSUE THREAD

**Issue by tiquis0290** [the-marenga/sf-api#59]
pets doesn't have command to attack at habitat and attack  other player's pets

**Comment by the-marenga** [comment]
Yeah, thanks for pointing that out. I just checked and the commands are:

`PetsDungeonFight:{use_mushroom}/{habitat_id}/{enemy_pos(1-20?)}/{player_pet_id}`
and 
`PetsPvPFight:0/{enemy_id}/{habitat_id}`

(posting them here so I do not forget)

Need to test them a bit to make sure they work, but should be relatively easy to add to the regular commands
