### ISSUE TITLE
idlegame update

### ISSUE THREAD

**Issue by tiquis0290** [the-marenga/sf-api#61]
when i looked at idlegame i find out that idlesave that get sent to client is not automaticcly updated, i guess there should be another command for updating state of idlegame

**Comment by the-marenga** [comment]
I don't think there is a way to only update the idle game. The game itself sends `UpdatePlayer`(poll) commands from time to time, which amongst other things updates the idle game. 

Does that not work for you?

**Comment by tiquis0290** [comment]
thx, i played with this command and for some reason i thought that it only returned timestamp, so i never used it and always wondered why its here
