### ISSUE TITLE
Allow claiming of items from the ingame Mailbox 

### ISSUE THREAD

**Issue by alexb231** [the-marenga/sf-api#66]
Hey, so as of right now there is no way to use the API to claim items sent to the ingame Mailbox e.g. Twitch Drops, Gift Codes.

Would be nice to have that possibility as well. 

Thanks a lot.

**Comment by the-marenga** [comment]
Thanks for mentioning gift codes! I always thought the only way to get items in the mailbox would be twitch drops and I never got any, so I could never parse them, or reverse engineer the command to claim them. 

But yeah, gift codes seem to work, so I will get have a look at implementing that

**Comment by alexb231** [comment]
> Thanks for mentioning gift codes! I always thought the only way to get items in the mailbox would be twitch drops and I never got any, so I could never parse them, or reverse engineer the command to claim them.
> 
> But yeah, gift codes seem to work, so I will get have a look at implementing that
If it helps i can provide you an account with claimable drops.

**Comment by the-marenga** [comment]
> If it helps i can provide you an account with claimable drops.

Thanks for the offer, but in this case I was able to reverse engineer everything by using my custom S&F server and modifying the values from the initial gift code item a bit: 

![grafik](https://github.com/the-marenga/sf-api/assets/107524538/eb2555e7-8271-4405-8535-eb3686dc68b6)

Support for all of this should land on the main branch either today, or tomorrow. Might take a few more days, until that makes it to the official crates.io release.
