### ISSUE TITLE
Event [Ruffian Reset] rewards aren't correctly parsed in the Gamestate

### ISSUE THREAD

**Issue by alexb231** [the-marenga/sf-api#76]
It's possible that other events are affected too, but this one specifically retrieves wrong Reward informations causing the Gamestate not to update correctly it seems. 

This weeks rewards: 
Rewards: [RewardChest { opened: true, reward: [Some(Reward { typ: Stone, amount: 3120 }), None] }, RewardChest { opened: false, reward: [Some(Reward { typ: ExtraBeer, amount: 1 }), None] }, RewardChest { opened: false, reward: [Some(Reward { typ: Mushroom, amount: 2 }), None] }]

0. Metal/Crystal is displayed as stone thats fine thats probably just a naming thing
1. Says Reward is Beer -> Should be gold 
2. Says Mushrooms -> Should be an extra beer (12th Beer) 

Anyway, it seems claiming those chests doesnt update the Gamestate correctly, assumption would be its not the correct chest that was actually claimed ? 

Repro step: 

Check the GameState under:
specials.tasks.event.rewards and compare it to the tasks in SF.

BTW: All of the RewardChests were already claimed already at the point of opening this issue. 

Thanks

**Comment by the-marenga** [comment]
Seems like they changed the mapping of the event rewards again. Seems like a good point in time to also finally fix #48. I am going to start working on that
