### ISSUE TITLE
session.game_state().unwrap() error

### ISSUE THREAD

**Issue by DrobnyV** [the-marenga/sf-api#84]
Hey this is my code:

    let sessions = SimpleSession::login_sf_account(
        "username",
        "password"
    ).await.unwrap();

    for mut session in sessions {
        let gs = session;
        let test = gs.game_state().unwrap();
        break
    }

Why does let test = gs.game_state().unwrap(); throws called `Option::unwrap()` on a `None` value.
Sorry it its stupid question but I do not know what to do.

And while I'm writing this post I would like to ask one more question about decrypting urls.
I tried to find the login response but couldn't.
This is what I got when I logged into the test account.
![image](https://github.com/user-attachments/assets/db72ffc1-a30b-4b46-850d-0f21074f69c9)

**Comment by the-marenga** [comment]
I assume you fixed the api error yourself. 

If you are still looking for the login response, you can find it in the response tab, not the header tab. This also looks like a request to the SSO server, which contains your credentials to your sso account, but the character login response will be in the first response to the actual game server (~f2.sfgame.net), not sso.playa-games.com.

**Comment by DrobnyV** [comment]
Yeah I fixed the api error. And thanks to you I found the login response so thanks!
